### ISSUE TITLE
Building the benchmark fails

### ISSUE THREAD

**Issue by llogiq** [vks/bytecounttest#1]
I try `RUSTC_FLAGS="-C target-cpu=native" cargo bench`, but the *build script* fails with `SIGILL`. Using rustc nightly as of 2017-02-27. By the way, building and linking the C library is successful.

I'm running on a Core m3y60, which has avx and avx2, if that helps.

**Comment by vks** [comment]
Where exactly does it fail? The only thing the build script does is building and linking the static C library...

I would expect the *benchmarking* of the C library to fail with SIGILL if there is no AVX2.

**Comment by llogiq** [comment]
The build script failed because of a LLVM problem, it appears. Using `RUSTFLAGS="-C target-cpu=skylake"` instead of `native` solved the problem for me. My results (using `rustc 1.18.0-nightly (5309a3e31 2017-04-03)`):

```
running 8 tests
test bench_count               ... bench:          47 ns/iter (+/- 2)
test bench_naive_count         ... bench:         568 ns/iter (+/- 58)
test bench_newlinecount_avx    ... bench:         100 ns/iter (+/- 1)
test bench_newlinecount_avxu   ... bench:          63 ns/iter (+/- 6)
test bench_newlinecount_avxuu  ... bench:          79 ns/iter (+/- 4)
test bench_newlinecount_basic  ... bench:         735 ns/iter (+/- 77)
test bench_newlinecount_memchr ... bench:         693 ns/iter (+/- 68)
test bench_newlinecount_swar   ... bench:         657 ns/iter (+/- 85)
```

cc @lemire

**Comment by llogiq** [comment]
Further analysis shows that:

* count(..) is not inlined
* most of the time is spent in an unrolled loop that looks like
```
  2010  1.6805 :   13c50:       vpcmpeqb (%rcx),%ymm0,%ymm3
  3234  2.7038 :   13c54:       vpsubb %ymm3,%ymm2,%ymm2
  3284  2.7456 :   13c58:       vpcmpeqb 0x20(%rcx),%ymm0,%ymm3
  4126  3.4495 :   13c5d:       vpsubb %ymm3,%ymm2,%ymm2
  3776  3.1569 :   13c61:       vpcmpeqb 0x40(%rcx),%ymm0,%ymm3
  3017  2.5224 :   13c66:       vpsubb %ymm3,%ymm2,%ymm2
  4030  3.3693 :   13c6a:       vpcmpeqb 0x60(%rcx),%ymm0,%ymm3
  3655  3.0558 :   13c6f:        vpsubb %ymm3,%ymm2,%ymm2
  etc.
```

**Comment by vks** [comment]
Thanks for the update! I updated the README to include this known issue (eea846a4410eb0b740f65984f75efdb02e733c52).
